---
kind: Service
apiVersion: v1
metadata:
  name: '{{ .Values.PUBLIC_FB_SERVICE_NAME }}'
  annotations:
    qubership.cloud/start.stage: '1'
  labels:
    app.kubernetes.io/name: '{{ .Values.PUBLIC_FB_SERVICE_NAME }}'
    app.kubernetes.io/instance: '{{ cat .Values.PUBLIC_FB_SERVICE_NAME "-" .Values.NAMESPACE | nospace | trunc 63 | trimSuffix "-" }}'
    app.kubernetes.io/component: '{{ .Values.SERVICE_NAME }}'
    app.kubernetes.io/part-of: 'Cloud-Core'
    app.kubernetes.io/managed-by: Helm
spec:
  ports:
    - name: web
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    name: '{{ .Values.PUBLIC_SERVICE }}'
  clusterIP: None
  clusterIPs:
    - None
  type: ClusterIP
  sessionAffinity: None
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  internalTrafficPolicy: Cluster 
---
kind: Service
apiVersion: v1
metadata:
  name: '{{ .Values.PRIVATE_FB_SERVICE_NAME }}'
  annotations:
    qubership.cloud/start.stage: '1'
  labels:
    app.kubernetes.io/name: '{{ .Values.PRIVATE_FB_SERVICE_NAME }}'
    app.kubernetes.io/instance: '{{ cat .Values.PRIVATE_FB_SERVICE_NAME "-" .Values.NAMESPACE | nospace | trunc 63 | trimSuffix "-" }}'
    app.kubernetes.io/component: '{{ .Values.SERVICE_NAME }}'
    app.kubernetes.io/part-of: 'Cloud-Core'
    app.kubernetes.io/managed-by: Helm
spec:
  ports:
    - name: web
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    name: '{{ .Values.PRIVATE_SERVICE }}'
  clusterIP: None
  clusterIPs:
    - None
  type: ClusterIP
  sessionAffinity: None
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  internalTrafficPolicy: Cluster 
