apiVersion: v1
kind: ConfigMap
metadata:
  name: ratelimit-config
  labels:
    app: ratelimit
    rate-limit-config: "true"
data:
  config.yaml: |
    domain: {{ .Values.config.domain | default "auth_limit" }}
    separator: {{ .Values.config.separator | default "|" }}
    descriptors:
      {{- if .Values.config.rateLimits.default }}
      - key: ""
        rate_limit:
          unit: {{ .Values.config.rateLimits.default.window | default "minute" }}
          requests_per_unit: {{ .Values.config.rateLimits.default.limit | default 60 }}
      {{- end }}
      {{- range .Values.config.rateLimits.rules }}
      - key: path
        value: {{ .pattern | quote }}
        rate_limit:
          unit: {{ .window | default "minute" }}
          requests_per_unit: {{ .limit }}
        descriptors:
        - key: user_id
          rate_limit:
            unit: {{ .window | default "minute" }}
            requests_per_unit: {{ .limit }}
      {{- end }}