apiVersion: v1
kind: ConfigMap
metadata:
  name: ratelimit-config
  labels:
    app: ratelimit
data:
  config.yaml: |
    domain: {{ .Values.config.domain | quote }}
    separator: {{ .Values.config.separator | quote }}
    descriptors:
      {{- if .Values.config.rateLimits.default }}
      - key: ""
        rate_limit:
          unit: {{ .Values.config.rateLimits.default.window | replace "s" "" | replace "m" "" | replace "h" "" | replace "d" "" }}
          requests_per_unit: {{ .Values.config.rateLimits.default.limit }}
      {{- end }}
      {{- range .Values.config.rateLimits.rules }}
      - key: path
        value: {{ .pattern | quote }}
        rate_limit:
          unit: {{ .window | replace "s" "" | replace "m" "" | replace "h" "" | replace "d" "" }}
          requests_per_unit: {{ .limit }}
        descriptors:
        - key: user_id
          rate_limit:
            unit: {{ .window | replace "s" "" | replace "m" "" | replace "h" "" | replace "d" "" }}
            requests_per_unit: {{ .limit }}
      {{- end }}