apiVersion: v1
kind: Service
metadata:
  name: ratelimit-api
  labels:
    app: ratelimit
    service: api
spec:
  selector:
    app: ratelimit
  ports:
  - name: api
    port: {{ .Values.api.port }}
    targetPort: api
    protocol: TCP
  - name: metrics
    port: {{ .Values.metrics.port }}
    targetPort: metrics
    protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: ratelimit-metrics
  namespace: {{ .Values.namespace }}
  labels:
    app: ratelimit
    service: metrics
spec:
  selector:
    app: ratelimit
  ports:
  - name: metrics
    port: {{ .Values.metrics.port }}
    targetPort: metrics
    protocol: TCP
  type: ClusterIP