kind: ServiceAccount
apiVersion: v1
metadata:
  name: control-plane
  namespace: cloud-core
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: Cloud-Core
    deployment.qubership.org/sessionId: 'cloud-core-local-dev'
    type: m2m 