apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq-1
  template:
    metadata:
      labels:
        app: rabbitmq-1
    spec:
      containers:
        - name: rabbitmq-1
          image: rabbitmq:3.8-rc-management-alpine
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: "admin"
            - name: RABBITMQ_DEFAULT_PASS
              value: "admin"
          ports:
            - containerPort: 5672
            - containerPort: 15672
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-1
spec:
  selector:
    app: rabbitmq-1
  ports:
    - name: amqp
      protocol: TCP
      port: 5672
      targetPort: 5672
    - name: management
      protocol: TCP
      port: 15672
      targetPort: 15672
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq-2
  template:
    metadata:
      labels:
        app: rabbitmq-2
    spec:
      containers:
        - name: rabbitmq-2
          image: rabbitmq:3.8-rc-management-alpine
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: "admin"
            - name: RABBITMQ_DEFAULT_PASS
              value: "admin"
          ports:
            - containerPort: 5672
            - containerPort: 15672
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-2
spec:
  selector:
    app: rabbitmq-2
  ports:
    - name: amqp
      protocol: TCP
      port: 5672
      targetPort: 5672
    - name: management
      protocol: TCP
      port: 15672
      targetPort: 15672
  type: NodePort