postgresPassword: ${POSTGRES_PASSWORD}

backupDaemon:
  storage:
    storageClass: ${STORAGE_CLASS}
dbaas:
  install: true
  aggregator:
    registrationAddress: http://${DBAAS_SERVICE_NAME}.${DBAAS_NAMESPACE}.svc.cluster.local:8080
    registrationUsername: cluster-dba
    registrationPassword: password
