---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.SERVICE_NAME }}-prehook-role
  namespace: {{ .Values.NAMESPACE }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-weight": "-194"
    "helm.sh/hook-delete-policy": "before-hook-creation, hook-succeeded"
  labels:
    app.kubernetes.io/instance: "{{ .Values.SERVICE_NAME }}"
    app.kubernetes.io/part-of: Cloud-Core
    app.kubernetes.io/managed-by: "helm"
    deployment.netcracker.com/sessionId: '{{ .Values.DEPLOYMENT_SESSION_ID }}'
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
      - serviceaccounts
      - configmaps
    verbs:
      - get
      - list
      - create
      - update
      - patch
  - apiGroups:
      - ""
    resources:
      - services
      - configmaps
      - pods
    verbs:
      - delete
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - delete
  - apiGroups:
      - autoscaling
    resources:
      - horizontalpodautoscalers
    verbs:
      - delete
  - apiGroups:
      - monitoring.coreos.com
    resources:
      - podmonitors
    verbs:
      - delete