---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.SERVICE_NAME }}-prehook-rb
  namespace: {{ .Values.NAMESPACE }}
  annotations:
    "helm.sh/hook": "pre-install, pre-upgrade"
    "helm.sh/hook-weight": "-193"
    "helm.sh/hook-delete-policy": "before-hook-creation, hook-succeeded"
  labels:
    app.kubernetes.io/instance: "{{ .Values.SERVICE_NAME }}"
    app.kubernetes.io/part-of: Cloud-Core
    app.kubernetes.io/managed-by: "helm"
    deployment.netcracker.com/sessionId: '{{ .Values.DEPLOYMENT_SESSION_ID }}'
subjects:
  - kind: ServiceAccount
    name: {{ .Values.SERVICE_NAME }}-sa
    namespace: {{ .Values.NAMESPACE }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Values.SERVICE_NAME }}-prehook-role
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.SERVICE_NAME }}-prehook-rb-default
  namespace: {{ .Values.NAMESPACE }}
  annotations:
    "helm.sh/hook": "pre-install, pre-upgrade"
    "helm.sh/hook-weight": "-193"
    "helm.sh/hook-delete-policy": "before-hook-creation, hook-succeeded"
  labels:
    app.kubernetes.io/instance: "{{ .Values.SERVICE_NAME }}"
    app.kubernetes.io/part-of: Cloud-Core
    app.kubernetes.io/managed-by: "helm"
    deployment.netcracker.com/sessionId: '{{ .Values.DEPLOYMENT_SESSION_ID }}'
subjects:
  - kind: ServiceAccount
    name: default
    namespace: {{ .Values.NAMESPACE }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Values.SERVICE_NAME }}-prehook-role