---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.SERVICE_NAME }}-env-variables
  annotations:
    helm.sh/hook: "pre-install,pre-upgrade"
    helm.sh/hook-weight: "-192"
    helm.sh/hook-delete-policy: "before-hook-creation, hook-succeeded"
  labels:
    app.kubernetes.io/instance: {{ .Values.SERVICE_NAME }}
    app.kubernetes.io/part-of: Cloud-Core
    app.kubernetes.io/managed-by: "helm"
    deployment.netcracker.com/sessionId: '{{ .Values.DEPLOYMENT_SESSION_ID }}'
stringData:
  NAMESPACE: {{ .Values.NAMESPACE | quote }}
  SERVICE_NAME: {{ .Values.SERVICE_NAME | quote }}
  BASELINE_ORIGIN: {{ .Values.BASELINE_ORIGIN | quote }}
  ORIGIN_NAMESPACE: {{ .Values.ORIGIN_NAMESPACE | quote }}
  DBAAS_LODB_PER_NAMESPACE_AUTOBALANCE_RULES: {{ .Values.DBAAS_LODB_PER_NAMESPACE_AUTOBALANCE_RULES | quote }}
  DBAAS_AGGREGATOR_ADDRESS: {{ .Values.DBAAS_AGGREGATOR_ADDRESS | quote }}
  STAAS_ENABLED: {{ .Values.STAAS_ENABLED | quote }}
  API_DBAAS_ADDRESS: {{ .Values.API_DBAAS_ADDRESS | quote }}
  STAAS_INTERNAL_ADDRESS: {{ .Values.STAAS_INTERNAL_ADDRESS | quote }}
  DBAAS_CLUSTER_DBA_CREDENTIALS_USERNAME: {{ .Values.DBAAS_CLUSTER_DBA_CREDENTIALS_USERNAME | quote }}
  DBAAS_CLUSTER_DBA_CREDENTIALS_PASSWORD: {{ .Values.DBAAS_CLUSTER_DBA_CREDENTIALS_PASSWORD | quote }}
  IDP_ADMIN_USER_NAME: {{ .Values.IDP_ADMIN_USER_NAME | quote }}
  IDP_ADMIN_USER_PASSWORD: {{ .Values.IDP_ADMIN_USER_PASSWORD | quote }}
  IDP_DB_CREDENTIALS_SECRET: {{ .Values.IDP_DB_CREDENTIALS_SECRET | quote }}
  CONSUL_ENABLED: {{ .Values.CONSUL_ENABLED | quote }}
  CONSUL_PUBLIC_URL: {{ .Values.CONSUL_PUBLIC_URL | quote }}
  CONSUL_ADMIN_TOKEN: {{ .Values.CONSUL_ADMIN_TOKEN | quote }}
  POLICY_ID: {{ .Values.POLICY_ID | quote }}
  MAAS_ENABLED: {{ .Values.MAAS_ENABLED | quote }}
  MAAS_CREDENTIALS_USERNAME: {{ .Values.MAAS_CREDENTIALS_USERNAME | quote }}
  MAAS_CREDENTIALS_PASSWORD: {{ .Values.MAAS_CREDENTIALS_PASSWORD | quote }}
  MAAS_INTERNAL_ADDRESS: {{ .Values.MAAS_INTERNAL_ADDRESS | quote }}
  DC_NAME: {{ .Values.DC_NAME | quote }}
  DBAAS_ON_MICROSERVICES_PHYSDB_RULE: {{ .Values.DBAAS_ON_MICROSERVICES_PHYSDB_RULE | quote }}
  MAAS_CONFIG: {{ .Values.MAAS_CONFIG | quote }}
