---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    "helm.sh/hook": "pre-install, pre-upgrade"
    "helm.sh/hook-weight": "-195"
    "helm.sh/hook-delete-policy": "before-hook-creation, hook-succeeded"
  name: '{{ .Values.SERVICE_NAME }}-sa'
  namespace: '{{ .Values.NAMESPACE }}'
  labels:
    app.kubernetes.io/instance: "{{ .Values.SERVICE_NAME }}"
    app.kubernetes.io/part-of: Cloud-Core
    app.kubernetes.io/managed-by: "helm"
    deployment.netcracker.com/sessionId: '{{ .Values.DEPLOYMENT_SESSION_ID }}'